#
# This compose file spins up a Redis + Postgres container for development
#

volumes:
  pg-data:

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: user
    volumes:
      - pg-data:/var/lib/postgresql/data
